# SITE CONFIGURATION
baseurl: "" # pokud není potřeba podadresář
url: "http://localhost:4000" # základní URL při lokálním vývoji
lang: "cs"

# THEME-SPECIFIC CONFIGURATION
title: Vybavení do přírody                              # site's title
description: "Výbava na outdoor a cesty do přírody"     # used by search engines
avatar: assets/img/patrick.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Výbavu na trail, do hor, do přírody? Poradím!  # Change Blog header text
header_feature_image: assets/img/header/triangular.jpeg
header_feature_image_responsive: true
footer_text: >
  Vytváří <a href="https://www.marigold.cz">Patrick Zandl</a> s pomocí <a href="https://pages.cloudflare.com">Cloudflare Pages</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: false                                            # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Measurement ID, e.g. "G-00000"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: light                                       # auto, dark or light

# Comments options
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 10
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  categories:
    output: true
    permalink: /:name/
    folder: _categories

# BUILD SETTINGS
sass:
  style: compressed
  quiet_deps: true
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]
extra_css: 
  - "/assets/css/custom.css"
  - "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Open+Sans:wght@400;600&display=swap"

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github

# Změna formátu permalinků
permalink: /:categories/:title/
