# Definice produktů pro automatické linkování
# Každý produkt obsahuje:
# - name: Hodnota z front matter (pole model) – přesný název produktu
# - url: Relativní URL na stránku s recenzí nebo detailním popisem produktu
# - variants: Pole alternativních názvů produktu, je-li nutné
# - generování probíhá v _plugins/product_linker.rb přes: ruby scripts/generate_products.rb
- name: Bach Molecule 45L
  url: "/batohy/bach-molecule-45l/"
  variants:
  - Bach Molecule
- name: Bach Specialist 70L Women
  url: "/batohy/bach-specialist-70l/"
  variants:
  - Bach Specialist
- name: Bach Specialist 90L
  url: "/batohy/bach-specialist-90l/"
  variants:
  - Bach Specialist
- name: Black Diamond Cirque 35L
  url: "/batohy/black-diamond-cirque-35l/"
  variants:
  - Black Diamond Cirque
- name: Black Diamond Creek Transit 30L
  url: "/batohy/black-diamond-creek-transit-20l-30l/"
  variants:
  - Black Diamond Creek Transit
- name: Black Diamond Infinity 60
  url: "/batohy/black-diamond-infinity-60l/"
  variants:
  - Black Diamond Infinity
- name: Black Diamond Mission 75
  url: "/batohy/black-diamond-mission-45l-75l/"
  variants:
  - Black Diamond Mission
- name: Black Diamond Speed 30
  url: "/batohy/black-diamond-speed-22l-30l/"
  variants:
  - Black Diamond Speed
- name: Deuter AirContact 65+10
  url: "/batohy/deuter-aircontact-55-10-deuter-aircontact-65-10-deuter-aircontact-75-10/"
  variants:
  - Deuter AirContact
- name: Deuter AirContact Lite 45 SL
  url: "/batohy/deuter-aircontact-lite-45-sl-deuter-aircontact-lite-50-sl/"
  variants:
  - Deuter AirContact Lite
- name: Deuter Attack 22
  url: "/batohy/deuter-attack-20-deuter-attack-24/"
  variants:
  - Deuter Attack
- name: Deuter Futura 42
  url: "/batohy/deuter-futura-32-deuter-futura-42-deuter-futura-52/"
  variants:
  - Deuter Futura
- name: Deuter Giga 28
  url: "/batohy/deuter-giga-28-deuter-giga-32/"
  variants:
  - Deuter Giga
- name: Deuter Guide 40+
  url: "/batohy/deuter-guide-32-deuter-guide-40/"
  variants:
  - Deuter Guide
- name: Deuter Speed Lite 24
  url: "/batohy/deuter-speed-lite-20-deuter-speed-lite-24-deuter-speed-lite-27/"
  variants:
  - Deuter Speed Lite
- name: Deuter Trail 30
  url: "/batohy/deuter-trail-26-deuter-trail-30-deuter-trail-32/"
  variants:
  - Deuter Trail
- name: Deuter Trans Alpine 30
  url: "/batohy/deuter-trans-alpine-28-deuter-trans-alpine-30/"
  variants:
  - Deuter Trans Alpine
- name: Dynafit Alpine Pro
  url: "/boty/dynafit-alpine-pro/"
  variants: []
- name: Dynafit Speed MTN GTX
  url: "/boty/dynafit-speed-mtn-gtx/"
  variants: []
- name: Dynafit Ultra 100
  url: "/boty/dynafit-ultra-100/"
  variants:
  - Dynafit Ultra
- name: Garmont Toubkal GTX
  url: "/boty/garmont-toubkal-gtx/"
  variants: []
- name: Garmont Vetta GTX
  url: "/boty/garmont-vetta-gtx/"
  variants: []
- name: Gregory Amber 44
  url: "/batohy/gregory-amber-44-gregory-amber-54/"
  variants:
  - Gregory Amber
- name: Gregory Baltoro 85
  url: "/batohy/gregory-baltoro-85/"
  variants:
  - Gregory Baltoro
- name: Gregory Deva 60
  url: "/batohy/gregory-deva-60-gregory-deva-70/"
  variants:
  - Gregory Deva
- name: Gregory Facet 45
  url: "/batohy/gregory-facet-45/"
  variants:
  - Gregory Facet
- name: Gregory Facet 55
  url: "/batohy/gregory-facet-45-gregory-facet-55/"
  variants:
  - Gregory Facet
- name: Gregory Focal 58, Gregory Focal 68
  url: "/batohy/gregory-focal-58-gregory-focal-68/"
  variants:
  - Gregory Focal
- name: Gregory Jade 63
  url: "/batohy/gregory-jade-53-gregory-jade-63/"
  variants:
  - Gregory Jade
- name: Gregory Katmai 55, Gregory Katmai 65
  url: "/batohy/gregory-katmai-55-gregory-katmai-65/"
  variants:
  - Gregory Katmai
- name: Gregory Maven 55, Gregory Maven 65
  url: "/batohy/gregory-maven-55-gregory-maven-65/"
  variants:
  - Gregory Maven
- name: Gregory Octal 55
  url: "/batohy/gregory-octal-55-gregory-octal-65/"
  variants:
  - Gregory Octal
- name: Gregory Optic 48
  url: "/batohy/gregory-optic-48-gregory-optic-58/"
  variants:
  - Gregory Optic
- name: Gregory Paragon 58
  url: "/batohy/gregory-paragon-48-gregory-paragon-58/"
  variants:
  - Gregory Paragon
- name: Gregory Stout 45
  url: "/batohy/gregory-stout-45-gregory-stout-60/"
  variants:
  - Gregory Stout
- name: Gregory Targhee 45, Gregory Targhee 55
  url: "/batohy/gregory-targhee-45-gregory-targhee-55/"
  variants:
  - Gregory Targhee
- name: Gregory Zulu 55
  url: "/batohy/gregory-zulu-40-gregory-zulu-55/"
  variants:
  - Gregory Zulu
- name: Klymit Insulated Static V
  url: "/karimatky/klymit-insulated-static-v/"
  variants: []
- name: Klymit Klymaloft Regular
  url: "/karimatky/klymit-klymaloft/"
  variants: []
- name: Klymit Static V
  url: "/karimatky/klymit-static-v/"
  variants: []
- name: Klymit Static V Luxe
  url: "/karimatky/klymit-static-v-luxe/"
  variants: []
- name: Klymit Static V2
  url: "/karimatky/klymit-static-v2/"
  variants:
  - Klymit Static V
- name: Lowe Alpine Aeon 27, Aeon 35
  url: "/batohy/lowe-alpine-aeon-27-aeon-35/"
  variants:
  - Lowe Alpine Aeon
- name: Lowe Alpine AirZone Pro 35, AirZone Pro 45
  url: "/batohy/lowe-alpine-airzone-pro-35-airzone-pro-45/"
  variants:
  - Lowe Alpine AirZone Pro
- name: Lowe Alpine AirZone Trail 35
  url: "/batohy/lowe-alpine-airzone-trail-35-airzone-trail-40-airzone-trail-45/"
  variants:
  - Lowe Alpine AirZone Trail
- name: Lowe Alpine AirZone Trail Camino ND35-40
  url: "/batohy/lowe-alpine-airzone-trail-nd-35-airzone-trail-nd-40-airzone-trail-nd-45/"
  variants:
  - Lowe Alpine AirZone Trail Camino ND
- name: Lowe Alpine Altus 52:57
  url: "/batohy/lowe-alpine-altus-52-57/"
  variants:
  - Lowe Alpine Altus
- name: Lowe Alpine Cholatse 50
  url: "/batohy/lowe-alpine-cholatse-44-cholatse-50-cholatse-55/"
  variants:
  - Lowe Alpine Cholatse
- name: Lowe Alpine Cholatse 50 ND
  url: "/batohy/lowe-alpine-cholatse-44-nd-cholatse-50-nd-cholatse-55-nd/"
  variants:
  - Lowe Alpine Cholatse
- name: Lowe Alpine Manaslu 60
  url: "/batohy/lowe-alpine-manaslu-55-manaslu-60-manaslu-65/"
  variants:
  - Lowe Alpine Manaslu
- name: Lowe Alpine TFX Cerro Torre 55
  url: "/batohy/lowe-alpine-tfx-cerro-torre-45-tfx-cerro-torre-55-tfx-cerro-torre-65/"
  variants:
  - Lowe Alpine TFX Cerro Torre
- name: Lowe Alpine TFX Cerro Torre 55+10
  url: "/batohy/lowe-alpine-tfx-cerro-torre-45-10-tfx-cerro-torre-55-10-tfx-cerro-torre-65-10/"
  variants:
  - Lowe Alpine TFX Cerro Torre
- name: Osprey Ariel 65
  url: "/batohy/osprey-ariel-55-osprey-ariel-65-osprey-ariel-75/"
  variants:
  - Osprey Ariel
- name: Osprey Atmos AG 65
  url: "/batohy/osprey-atmos-ag-50-osprey-atmos-ag-65/"
  variants:
  - Osprey Atmos AG
- name: Osprey Aura AG 65
  url: "/batohy/osprey-aura-ag-50-osprey-aura-ag-65/"
  variants:
  - Osprey Aura AG
- name: Osprey Eja 58
  url: "/batohy/osprey-eja-48-osprey-eja-58/"
  variants:
  - Osprey Eja
- name: Osprey Exos 48
  url: "/batohy/osprey-exos-48-osprey-exos-58/"
  variants:
  - Osprey Exos
- name: Osprey Hikelite 26
  url: "/batohy/osprey-hikelite-26/"
  variants:
  - Osprey Hikelite
- name: Osprey Kestrel 48
  url: "/batohy/osprey-kestrel-38-osprey-kestrel-48-osprey-kestrel-58/"
  variants:
  - Osprey Kestrel
- name: Osprey Kyte 36 a 46
  url: "/batohy/osprey-kyte-36-osprey-kyte-46/"
  variants:
  - Osprey Kyte
- name: Osprey Rook 65
  url: "/batohy/osprey-rook-65/"
  variants:
  - Osprey Rook
- name: Osprey Sirrus 24
  url: "/batohy/osprey-sirrus-24-osprey-sirrus-34/"
  variants:
  - Osprey Sirrus
- name: Osprey Skarab 30
  url: "/batohy/osprey-skarab-18-osprey-skarab-22-osprey-skarab-30/"
  variants:
  - Osprey Skarab
- name: Osprey Stratos 36
  url: "/batohy/osprey-stratos-24-osprey-stratos-36-osprey-stratos-48/"
  variants:
  - Osprey Stratos
- name: Osprey Talon 33
  url: "/batohy/osprey-talon-22-osprey-talon-33-osprey-talon-44-osprey-talon-55/"
  variants:
  - Osprey Talon
- name: Osprey Volt 60
  url: "/batohy/osprey-volt-60/"
  variants:
  - Osprey Volt
- name: Osprey Xenith 88
  url: "/batohy/osprey-xenith-88/"
  variants:
  - Osprey Xenith
- name: Pajak Alpine
  url: "/karimatky/pajak-alpine/"
  variants: []
- name: Pajak Expedition
  url: "/karimatky/pajak-expedition/"
  variants: []
- name: Sea to Summit Ether Light XT
  url: "/karimatky/sea-to-summit-ether-light-xt/"
  variants: []
- name: Sea to Summit Ether Light XT Insulated
  url: "/karimatky/sea-to-summit-ether-light-xt-insulated/"
  variants: []
- name: Therm-a-Rest BaseCamp
  url: "/karimatky/therm-a-rest-basecamp/"
  variants: []
- name: Therm-a-Rest NeoAir Topo Luxe
  url: "/karimatky/therm-a-rest-neoair-topo-luxe/"
  variants: []
- name: Therm-a-Rest NeoAir XLite NXT MAX
  url: "/karimatky/Therm-a-Rest-NeoAir-XLite-NXT-MAX/"
  variants: []
- name: Therm-a-Rest NeoAir XTherm NXT
  url: "/karimatky/therm-a-rest-neoair-xtherm-nxt/"
  variants: []
- name: Therm-a-Rest ProLite Apex (Regular)
  url: "/karimatky/therm-a-rest-prolite-apex/"
  variants: []
- name: Therm-a-Rest RidgeRest Classic
  url: "/karimatky/therm-a-rest-ridgerest-classic/"
  variants: []
- name: Therm-a-Rest Trail Lite
  url: "/karimatky/therm-a-rest-trail-lite/"
  variants: []
- name: Therm-a-Rest Trail Pro
  url: "/karimatky/therm-a-rest-trail-pro/"
  variants: []
- name: Therm-a-Rest Trail Scout
  url: "/karimatky/therm-a-rest-trail-scout/"
  variants: []
- name: Therm-a-Rest Venture
  url: "/karimatky/therm-a-rest-venture/"
  variants: []
- name: Therm-a-Rest Z-Lite Sol
  url: "/karimatky/therm-a-rest-z-lite-sol/"
  variants: []
- name: Zulu Alex
  url: "/karimatky/zulu-alex/"
  variants: []
- name: Zulu Moonglight Comfort
  url: "/karimatky/zulu-moonglight/"
  variants: []

# ===== Konec automaticky generovaných položek =====
